/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kutuphane2;

import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.JOptionPane;

/**
 *
 * @author KÜRŞAD
 */
public class BilgiGuncelle extends javax.swing.JFrame {

    Kutuphane k;

    /**
     * Creates new form BilgiGuncelle
     */
    public BilgiGuncelle() {
        initComponents();
    }

    public BilgiGuncelle(Kutuphane k, String uyeisim, int id, String mesaj) {
        initComponents();
        this.k = k;
        UyeIdlabel.setText(Integer.toString(id));
        hedeflabel.setText(mesaj);
        belirtec.setText(uyeisim);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtYeni = new javax.swing.JTextField();
        Secim = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        belirtec = new javax.swing.JLabel();
        UyeIdlabel = new javax.swing.JLabel();
        hedeflabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        UyariLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 102));
        jLabel1.setText("Sayın kullanıcı güncellemek istediğiniz bilgiyi listeden secip Yeni bilgiyi aşağıdaki kutuya yazınız");

        Secim.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        Secim.setForeground(new java.awt.Color(0, 51, 255));
        Secim.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Isim", "Soyisim", "Telefon No", "Tc No" }));
        Secim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SecimActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 51, 153));
        jButton1.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jButton1.setText("Güncelle");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        belirtec.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        belirtec.setForeground(new java.awt.Color(255, 255, 255));

        UyeIdlabel.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        UyeIdlabel.setForeground(new java.awt.Color(255, 255, 255));

        hedeflabel.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        hedeflabel.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 255, 255));
        jLabel2.setText("Copyright © Yusuf Nadir Uzun 2020");

        jButton2.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jButton2.setText("Geri");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        UyariLabel.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        UyariLabel.setForeground(new java.awt.Color(255, 204, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Secim, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(99, 99, 99)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtYeni, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(UyariLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 913, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hedeflabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(belirtec, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(UyeIdlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(belirtec, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UyeIdlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hedeflabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UyariLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtYeni, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Secim, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   public void bilgiislemac() {
        for (int i = 0; i < k.uyeler.size(); i++) {
            if (UyeIdlabel.getText().equals(k.uyeler.get(i).isim)) {
                BilgiGuncelle guncel = new BilgiGuncelle(k, " Uye İsmi = " +k.uyeler.get(i).isim+ " Uye ID = " , k.uyeler.get(i).ID, " Uye soyismi = " + k.uyeler.get(i).soyisim + ", Uye Tel No = " + k.uyeler.get(i).no + ",  Uye Tc No = " + k.uyeler.get(i).tc);
                guncel.setVisible(true);
                setVisible(false);
            }
        }
    }


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("KutuphaneSonPU");
        EntityManager em = emf.createEntityManager();

        try {
            int uyeId = Integer.parseInt(UyeIdlabel.getText());
            for (int i = 0; i < k.uyeler.size(); i++) {
                if (k.uyeler.get(i).ID == uyeId) {

                   
                    if (Secim.getSelectedItem().equals("Isim")) {
                        if(txtYeni.getText().length()>2){
                        k.uyeler.get(i).isim = txtYeni.getText();
                         Query uyeq = em.createQuery("select u from Uye u");
                        List<Uye> uyelerDB = uyeq.getResultList();
                        for (Uye uye : uyelerDB) {
                            if (uye.getId() == k.uyeler.get(i).ID) {
                                em.getTransaction().begin();
                                uye.setAdi((txtYeni.getText()));
                                em.getTransaction().commit();
                                em.close();
                                emf.close();
                                JOptionPane.showMessageDialog(null, "Isim değiştirme işlemi başarılı", " başarılı işlem", JOptionPane.INFORMATION_MESSAGE);
                                UyariLabel.setText(" ");
                                int a = JOptionPane.showConfirmDialog(null, " Başka bir işlem yapmak istiyor musunuz ? ", " Pes mi Devam Mı ", JOptionPane.YES_NO_OPTION);
                                if (a == 1) {
                                    UyeSayfasi uyesayfa = new UyeSayfasi(k, " Uye İsmi = "+ k.uyeler.get(i).isim + " Uye ID = " ,k.uyeler.get(i).ID ," Uye soyismi = " + k.uyeler.get(i).soyisim + ", Uye Tel No = " + k.uyeler.get(i).no + ",  Uye Tc No = " + k.uyeler.get(i).tc);
                                    uyesayfa.setVisible(true);
                                    uyesayfa.setLocationRelativeTo(null);
                                    setVisible(false);
                                } else {
                                    bilgiislemac();
                                }
                            }
                        }
                    }
                        else{
                             UyariLabel.setText("Geçerli bir isim giriniz");
                            
                        }
                    }
                    if (Secim.getSelectedItem().equals("Soyisim")) {
                           if(txtYeni.getText().length()>2){
                               
                        k.uyeler.get(i).soyisim = txtYeni.getText();
                         Query uyeq = em.createQuery("select u from Uye u");
                        List<Uye> uyelerDB = uyeq.getResultList();
                        for (Uye uye : uyelerDB) {
                            if (uye.getId() == k.uyeler.get(i).ID) {
                                em.getTransaction().begin();
                                uye.setSoyisim(txtYeni.getText());
                                em.getTransaction().commit();
                                em.close();
                                emf.close();
                                JOptionPane.showMessageDialog(null, " Soyisim değiştirme işlemi başarılı", " başarılı işlem", JOptionPane.INFORMATION_MESSAGE);
                                UyariLabel.setText(" ");
                                int a = JOptionPane.showConfirmDialog(null, " Başka bir işlem yapmak istiyor musunuz ? ", " Pes mi Devam Mı ", JOptionPane.YES_NO_OPTION);
                                if (a == 1) {
                                    UyeSayfasi uyesayfa = new UyeSayfasi(k, " Uye İsmi = "+ k.uyeler.get(i).isim + " Uye ID = " ,k.uyeler.get(i).ID ," Uye soyismi = " + k.uyeler.get(i).soyisim + ", Uye Tel No = " + k.uyeler.get(i).no + ",  Uye Tc No = " + k.uyeler.get(i).tc);
                                    uyesayfa.setVisible(true);
                                    uyesayfa.setLocationRelativeTo(null);
                                    setVisible(false);
                                } else {
                                    bilgiislemac();
                                }
                            }

                    }
                    }else{
                               UyariLabel.setText("Geçerli bir soyisim giriniz");
                           }
                                  
                           }
                     
                    if (Secim.getSelectedItem().equals("Telefon No")) {
                        if(txtYeni.getText().length()<10|| txtYeni.getText().length() >10){
                            UyariLabel.setText("Tel No 10 Haneli Olmalıdır");
                        }else{
                        k.uyeler.get(i).no = (txtYeni.getText());
                          Query uyeq = em.createQuery("select u from Uye u");
                        List<Uye> uyelerDB = uyeq.getResultList();
                        for (Uye uye : uyelerDB) {
                            if (uye.getId() == k.uyeler.get(i).ID) {
                                em.getTransaction().begin();
                                uye.setTelno(txtYeni.getText());
                                em.getTransaction().commit();
                                em.close();
                                emf.close();
                                JOptionPane.showMessageDialog(null, " Telefon no değiştirme işlemi başarılı", " başarılı işlem", JOptionPane.INFORMATION_MESSAGE);
                                  UyariLabel.setText(" ");
                                int a = JOptionPane.showConfirmDialog(null, " Başka bir işlem yapmak istiyor musunuz ? ", " Pes mi Devam Mı ", JOptionPane.YES_NO_OPTION);
                                if (a == 1) {
                                    UyeSayfasi uyesayfa = new UyeSayfasi(k, " Uye İsmi = "+ k.uyeler.get(i).isim + " Uye ID = " ,k.uyeler.get(i).ID ," Uye soyismi = " + k.uyeler.get(i).soyisim + ", Uye Tel No = " + k.uyeler.get(i).no + ",  Uye Tc No = " + k.uyeler.get(i).tc);
                                    uyesayfa.setVisible(true);
                                    uyesayfa.setLocationRelativeTo(null);
                                    setVisible(false);
                                } else {
                                    bilgiislemac();
                                }
                            }
                        }
                    }
                    }


                    if (Secim.getSelectedItem().equals("Tc No")) {
                         if(txtYeni.getText().length()<11|| txtYeni.getText().length() >11){
                            UyariLabel.setText("Tc No 11 Haneli Olmalıdır");
                        }else{
                        k.uyeler.get(i).tc = (txtYeni.getText());
                        Query uyeq = em.createQuery("select u from Uye u");
                        List<Uye> uyelerDB = uyeq.getResultList();
                        for (Uye uye : uyelerDB) {
                            if (uye.getId() == k.uyeler.get(i).ID) {
                                em.getTransaction().begin();
                                uye.setTcno((txtYeni.getText()));
                                em.getTransaction().commit();
                                em.close();
                                emf.close();
                                JOptionPane.showMessageDialog(null, " Tc No değiştirme işlemi başarılı", " başarılı işlem", JOptionPane.INFORMATION_MESSAGE);
                                 UyariLabel.setText(" ");
                                int a = JOptionPane.showConfirmDialog(null, " Başka bir işlem yapmak istiyor musunuz ? ", " Pes mi Devam Mı ", JOptionPane.YES_NO_OPTION);
                                if (a == 1) {
                                    UyeSayfasi uyesayfa = new UyeSayfasi(k, " Uye İsmi = "+ k.uyeler.get(i).isim + " Uye ID = " ,k.uyeler.get(i).ID ," Uye soyismi = " + k.uyeler.get(i).soyisim + ", Uye Tel No = " + k.uyeler.get(i).no + ",  Uye Tc No = " + k.uyeler.get(i).tc);
                                    uyesayfa.setVisible(true);
                                    uyesayfa.setLocationRelativeTo(null);
                                    setVisible(false);
                                } else {
                                    bilgiislemac();
                                }
                            }
                        }
                        }
                    }
                }

            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, " Girdiginiz deger dogru değil");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        for (int i = 0; i < k.uyeler.size(); i++) {
            if (k.uyeler.get(i).ID==Integer.parseInt(UyeIdlabel.getText())) {
                UyeSayfasi uyesayfa = new UyeSayfasi(k, " Uye İsmi = " +k.uyeler.get(i).isim + " Uye ID = " , k.uyeler.get(i).ID," Uye soyismi = " + k.uyeler.get(i).soyisim + ", Uye Tel No = " + k.uyeler.get(i).no + ",  Uye Tc No = " + k.uyeler.get(i).tc);
                uyesayfa.setVisible(true);
                uyesayfa.setLocationRelativeTo(null);
                setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

        }
    }
    private void SecimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SecimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SecimActionPerformed
        
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BilgiGuncelle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BilgiGuncelle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BilgiGuncelle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BilgiGuncelle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BilgiGuncelle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Secim;
    private javax.swing.JLabel UyariLabel;
    private javax.swing.JLabel UyeIdlabel;
    private javax.swing.JLabel belirtec;
    private javax.swing.JLabel hedeflabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtYeni;
    // End of variables declaration//GEN-END:variables
}
