/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kutuphane2;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SpringLayout;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author KÜRŞAD
 */
public class UyeSayfasi extends javax.swing.JFrame {

    Kutuphane k;
    DefaultTableModel dtm = new DefaultTableModel();

    /**
     * Creates new form UyeSayfası
     */
    public UyeSayfasi() {
        initComponents();
        kitaplarList.setModel(dtm);
        KitapsayisiYaz();

    }

    public UyeSayfasi(Kutuphane k) {
        initComponents();
        this.k = k;
        KitapsayisiYaz();
        kitaplarList.setModel(dtm);

    }

    public UyeSayfasi(Kutuphane k, String uyeisim, int id, String mesaj) {
        initComponents();
        this.k = k;
        dtm.setColumnIdentifiers(new String[]{" ID ", "Kitap ismi", " Kitap Yazarı", "Kitap Sayfa"});
        kitaplarList.setModel(dtm);
        UyeidLabel.setText((Integer.toString(id)));
        hedeflabel.setText(mesaj);
        belirtec.setText(uyeisim);
        kitapListele();
        KitapsayisiYaz();
    }
    int sira = 1;

    /*
        String aranan = "[A-z]?[A-z]";
        String arananyer = Uyeisimlabel.getText();
        Pattern p = Pattern.compile(aranan);
        Matcher m = p.matcher(arananyer);
        System.out.println(m.group());
     */
    //
    public void kitapListele() {
        dtm.setRowCount(0);
        for (int i = 0; i < k.kitaplar.size(); i++) {
            dtm.addRow(new String[]{"" + k.kitaplar.get(i).ID, k.kitaplar.get(i).isim, k.kitaplar.get(i).yazar, "" + k.kitaplar.get(i).sayfa});

        }
    }

    public void KitapsayisiYaz() {
        for (UyeA uye : k.uyeler) {
            if (uye.ID == Integer.parseInt(UyeidLabel.getText())) {
                if (uye.UyeKitaplar.size() == 0) {
                    KitapSayısıyaz.setText("0");
                } else {
                    KitapSayısıyaz.setText("1");
                    KitapİsimLabel.setText("Üyede Bulunan Kitap İsmi:");
                    Kitapisim1label.setText(uye.UyeKitaplar.get(0).isim);
                }
            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        belirtec = new javax.swing.JLabel();
        UyeidLabel = new javax.swing.JLabel();
        hedeflabel = new javax.swing.JLabel();
        UyeyeKitapVer = new javax.swing.JButton();
        UyeyiTamamenSil = new javax.swing.JButton();
        UyedenKitapSil = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        kitaplarList = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        Geri = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        KitapSayısıyaz = new javax.swing.JLabel();
        KitapİsimLabel = new javax.swing.JLabel();
        Kitapisim1label = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(0, 51, 153));

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Uye Bilgileri :");

        belirtec.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        belirtec.setForeground(new java.awt.Color(255, 255, 255));

        UyeidLabel.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        UyeidLabel.setForeground(new java.awt.Color(255, 255, 255));

        hedeflabel.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        hedeflabel.setForeground(new java.awt.Color(255, 255, 255));

        UyeyeKitapVer.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        UyeyeKitapVer.setText("Uyeye Kitap Ver");
        UyeyeKitapVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UyeyeKitapVerActionPerformed(evt);
            }
        });

        UyeyiTamamenSil.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        UyeyiTamamenSil.setForeground(new java.awt.Color(255, 51, 51));
        UyeyiTamamenSil.setText("Bu Uyeyi Kutuphaneden Sil");
        UyeyiTamamenSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UyeyiTamamenSilActionPerformed(evt);
            }
        });

        UyedenKitapSil.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        UyedenKitapSil.setText("Uyeden Kitap Sil");
        UyedenKitapSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UyedenKitapSilActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 255, 255));
        jLabel2.setText("Kutuphanedeki Kitap Listesi;");

        kitaplarList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(kitaplarList);

        jLabel6.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 255, 255));
        jLabel6.setText("Copyright © Yusuf Nadir Uzun 2020");

        Geri.setBackground(new java.awt.Color(0, 102, 204));
        Geri.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        Geri.setForeground(new java.awt.Color(255, 255, 255));
        Geri.setText("Geri");
        Geri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeriActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 51, 204));
        jButton1.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Ana Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        jButton2.setText("Uye Bilgilerini Degistir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 102));
        jLabel3.setText("Sayın kullanıcı Uyeye Kitap vermek için listeden kitap secip kitap ver butonuna basınız.");

        jLabel4.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 255, 204));
        jLabel4.setText("Şu an uyede bulunan kitap sayısı :");

        KitapSayısıyaz.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        KitapSayısıyaz.setForeground(new java.awt.Color(255, 255, 255));

        KitapİsimLabel.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        KitapİsimLabel.setForeground(new java.awt.Color(204, 255, 204));

        Kitapisim1label.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        Kitapisim1label.setForeground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(belirtec, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UyeidLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hedeflabel, javax.swing.GroupLayout.PREFERRED_SIZE, 737, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 27, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(UyeyeKitapVer, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(60, 60, 60)
                                        .addComponent(UyedenKitapSil, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(70, 70, 70)
                                        .addComponent(jButton2)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(UyeyiTamamenSil)
                                .addGap(43, 43, 43))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(KitapSayısıyaz, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(KitapİsimLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Kitapisim1label, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(12, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Geri, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(belirtec, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UyeidLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hedeflabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Kitapisim1label, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(KitapİsimLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(KitapSayısıyaz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UyeyeKitapVer, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UyedenKitapSil, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UyeyiTamamenSil, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Geri, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(jLabel6)
                .addGap(521, 521, 521))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 894, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UyedenKitapSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UyedenKitapSilActionPerformed
        try {

            if (k.UyedenKitapSil(Integer.parseInt(UyeidLabel.getText()))) {
                k.DBuyedenKitapSil(Integer.parseInt(UyeidLabel.getText()));
                KitapSayısıyaz.setText("0");
                KitapİsimLabel.setText(" ");
                Kitapisim1label.setText(" ");
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, " Bilgileri tam giriniz ", " Uyarı", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_UyedenKitapSilActionPerformed

    private void UyeyiTamamenSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UyeyiTamamenSilActionPerformed
           k.DbSilinenUyeYaz(Integer.parseInt(UyeidLabel.getText()));
        if (k.UyeSil(Integer.parseInt(UyeidLabel.getText()))) {
            k.DBuyeSil(Integer.parseInt(UyeidLabel.getText()));
            System.out.println(UyeidLabel.getText());
            JOptionPane.showMessageDialog(null, " Uye Başarıyla Kutuphaneden Silindi", " Uye Silme Başarılı", JOptionPane.INFORMATION_MESSAGE);
            KayitliUye kayitliuye = new KayitliUye(k);
            kayitliuye.setVisible(true);
            kayitliuye.setLocationRelativeTo(null);
            setVisible(false);
        }
        else{
            k.DbSilinenuyeListedenSil(Integer.parseInt(UyeidLabel.getText()));
        }

    }//GEN-LAST:event_UyeyiTamamenSilActionPerformed
    int kitapsira = 1;
    private void UyeyeKitapVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UyeyeKitapVerActionPerformed
        try {
            if (k.KitapBaskasındaVarmı(Integer.parseInt((String) (dtm.getValueAt(kitaplarList.getSelectedRow(), 0))))) {
                System.out.println("baskası if içi");
                if (k.UyeyeKitapVer(Integer.parseInt(UyeidLabel.getText()), Integer.parseInt((String) (dtm.getValueAt(kitaplarList.getSelectedRow(), 0))))) {
                    k.DBuyeKitapEkle(Integer.parseInt((String) (dtm.getValueAt(kitaplarList.getSelectedRow(), 0))), (String) (dtm.getValueAt(kitaplarList.getSelectedRow(), 1)), (String) (dtm.getValueAt(kitaplarList.getSelectedRow(), 2)), Integer.parseInt((String) (dtm.getValueAt(kitaplarList.getSelectedRow(), 3))), Integer.parseInt(UyeidLabel.getText()));

                    System.out.println("şart sağlandı");
                    KitapSayısıyaz.setText("1");
                    KitapİsimLabel.setText("Üyede Bulunan Kitap İsmi:");
                    for (UyeA uye : k.uyeler) {
                        if (uye.ID == Integer.parseInt(UyeidLabel.getText())) {
                            Kitapisim1label.setText(uye.UyeKitaplar.get(0).isim);
                        }
                    }
                }
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, " Bilgileri tam giriniz ", " Uyarı", JOptionPane.ERROR_MESSAGE);
        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(null, " Listeden kitap seciniz ", " Uyarı", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_UyeyeKitapVerActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        AnaMenu anamenu = new AnaMenu(k);
        anamenu.setVisible(true);
        anamenu.setLocationRelativeTo(null);
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void GeriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeriActionPerformed
        KayitliUye kayitli = new KayitliUye(k);
        kayitli.setVisible(true);
        kayitli.setLocationRelativeTo(null);
        setVisible(false);
    }//GEN-LAST:event_GeriActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        for (int i = 0; i < k.uyeler.size(); i++) {
            if (Integer.parseInt(UyeidLabel.getText()) == k.uyeler.get(i).ID) {
                BilgiGuncelle bg = new BilgiGuncelle(k, " Uye İsmi = " + k.uyeler.get(i).isim + " Uye ID = ", k.uyeler.get(i).ID, " Uye soyismi = " + k.uyeler.get(i).soyisim + ", Uye Tel No = " + k.uyeler.get(i).no + ",  Uye Tc No = " + k.uyeler.get(i).tc);
                bg.setVisible(true);
                bg.setLocationRelativeTo(null);
                setVisible(false);

            }
        }


    }//GEN-LAST:event_jButton2ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UyeSayfasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UyeSayfasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UyeSayfasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UyeSayfasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UyeSayfasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Geri;
    private javax.swing.JLabel KitapSayısıyaz;
    private javax.swing.JLabel Kitapisim1label;
    private javax.swing.JLabel KitapİsimLabel;
    private javax.swing.JButton UyedenKitapSil;
    private javax.swing.JLabel UyeidLabel;
    private javax.swing.JButton UyeyeKitapVer;
    private javax.swing.JButton UyeyiTamamenSil;
    private javax.swing.JLabel belirtec;
    private javax.swing.JLabel hedeflabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable kitaplarList;
    // End of variables declaration//GEN-END:variables
}
